# Generated by Django 5.0.6 on 2024-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
