# Generated by Django 5.0.6 on 2024-05-13 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_question_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="votes",
        ),
    ]
