# Generated by Django 5.0.6 on 2024-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="job",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
