# Generated by Django 5.0.6 on 2024-07-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
