# Generated by Django 5.0.6 on 2024-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="type",
            field=models.CharField(
                choices=[(0, "Public Vocabulary"), (1, "Personal Vocabulary")],
                max_length=30,
            ),
        ),
    ]
