# Generated by Django 5.0.6 on 2024-07-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voca", "0002_profile_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalvocabulary",
            name="vocabulary_images",
            field=models.ImageField(
                blank=True, null=True, upload_to="vocabulary_images/"
            ),
        ),
        migrations.AddField(
            model_name="publicvocabulary",
            name="vocabulary_images",
            field=models.ImageField(
                blank=True, null=True, upload_to="vocabulary_images/"
            ),
        ),
    ]
