# Generated by Django 5.0.6 on 2024-05-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voca", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("meaning", models.TextField()),
                ("part_of_speech", models.CharField(max_length=50)),
                ("example_sentence", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WordBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="WordBookMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voca.word"
                    ),
                ),
                (
                    "word_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voca.wordbook"
                    ),
                ),
            ],
            options={
                "unique_together": {("word", "word_book")},
            },
        ),
        migrations.AddField(
            model_name="wordbook",
            name="words",
            field=models.ManyToManyField(
                through="voca.WordBookMembership", to="voca.word"
            ),
        ),
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("incorrect_count", models.PositiveIntegerField(default=0)),
                ("last_incorrect", models.BooleanField(default=False)),
                ("memo", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voca.user"
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voca.word"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "word")},
            },
        ),
        migrations.CreateModel(
            name="UserWordBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voca.user"
                    ),
                ),
                (
                    "word_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voca.wordbook"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "word_book")},
            },
        ),
    ]
