# Generated by Django 5.0.6 on 2024-05-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voca", "0003_word_wordbook_wordbookmembership_wordbook_words_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userword",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userword",
            name="word_book",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="voca.wordbook",
            ),
        ),
        migrations.AlterField(
            model_name="wordbook",
            name="words",
            field=models.ManyToManyField(
                related_name="word_books",
                through="voca.WordBookMembership",
                to="voca.word",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userword",
            unique_together={("user", "word", "word_book")},
        ),
    ]
