# Generated by Django 5.0.6 on 2024-08-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voca", "0004_vocabulary_unique_name_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="rank",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "비법 단어장"),
                    (2, "인증 단어장"),
                    (3, "일반 단어장"),
                    (4, "인증되지 않은 단어장"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Public Vocabulary"), (1, "Personal Vocabulary")]
            ),
        ),
    ]
