# Generated by Django 5.0.6 on 2024-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voca", "0005_alter_vocabulary_rank_alter_vocabulary_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
